#spring.data.mongodb.host=127.0.0.1
#spring.data.mongodb.port=27017
spring.data.mongodb.uri=mongodb+srv://gofood:Prajnesh%402001@cluster0.reyts.mongodb.net/
spring.data.mongodb.database=journaldb
#spring.data.mongodb.username=myusername
#spring.data.mongodb.password=mypassword

spring.data.mongodb.auto-index-creation=true    